applications:
  - name: my-nginx
    namespace: nginx
    repoURL: https://github.com/xchaths/argocd-app-of-apps.git
    targetRevision: main
    path: charts/apps/nginx
    project: default

  - name: todo-api
    namespace: todo-test
    repoURL: https://github.com/xchaths/argocd-app-of-apps.git
    targetRevision: main
    path: charts/apps/todo
    project: default